name: Lint

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: ESLint
        run: npm run lint:js

      - name: Markdownlint
        run: npm run lint:md

      - name: Prettier
        run: npm run lint:fmt
